const siteConfig = {
  name: "Ulcinj Car Rental",
  tagline: "Montenegro's Southern Coast",
  domain: "carrentalulcinj.com",
  phone: "",
  email: "info@carrentalulcinj.com",
  address: "Ulcinj, Montenegro",

  hero: {
    headline: "Ulcinj Car Rental — Montenegro's Southern Coast",
    subheadline: "Affordable car rental near Velika Plaza. 40km from Podgorica Airport, 75km from Tivat Airport.",
    image: "/img/hero-budva.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Beach Access", description: "Velika Plaza, Ada Bojana, and Valdanos are all within a short drive. Your car puts every beach on the southern coast within easy reach." },
    { icon: "shield-check", title: "Full Insurance", description: "CDW and theft cover included as standard. Upgrade to zero excess for total peace of mind on unpaved roads near Ada Bojana and coastal gravel tracks." },
    { icon: "clock", title: "24/7 Support", description: "Stuck at Velika Plaza after dark? Need a hand near Ada Bojana? Call us any hour — we know every road on the southern coast." },
    { icon: "ban", title: "No Hidden Fees", description: "One number at booking. That same number at pickup. VAT, mileage, and fuel policy are all baked in — nothing added at the counter." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Plans change. Cancel free up to 24 hours before your pickup and get every cent refunded." },
    { icon: "globe", title: "Cross-Border Ready", description: "Albania is 20 minutes away. Shkodra is a 45-minute drive, Tirana about 3 hours. Green card sorted at booking so you can cross without hassle." },
  ],

  testimonials: [
    { name: "Lars & Maja", location: "Copenhagen, Denmark", text: "We came for the kitesurfing at Ada Bojana and the car made everything so much easier. Drove out to the island each morning, explored the old town in the evenings. The roads near the river are rough but the Jeep handled it perfectly. Would rent again without question.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Sophie & Max", location: "Berlin, Germany", text: "Ulcinj's Ottoman old town is stunning but the real magic is having a car to explore beyond it. We drove to Valdanos one afternoon, found a completely empty olive grove beach, then headed to Stari Bar the next day. The freedom to move at our own pace made the trip.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "James & Claire", location: "London, UK", text: "We used Ulcinj as a base and did a day trip to Shkodra in Albania — only 45 minutes across the border. The green card was sorted before we arrived, so the crossing was painless. Also drove up to Lake Skadar for a boat tour. Having a car here is essential.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need to rent?", a: "You'll need a full driving licence with Latin-script details, your passport, and a physical credit card issued in the main driver's name. If your licence is from a country that uses a non-Latin script, bring an International Driving Permit as well. Photocopies and digital-only licences are not accepted at pickup." },
    { q: "Can I drive to Albania?", a: "Yes. Cross-border travel to Albania is permitted and very popular from Ulcinj — the Sukobin border crossing is about 20 minutes south. Shkodra is 45 minutes away, Tirana roughly 3 hours. Just flag Albania at booking and the Green Card is prepared for you." },
    { q: "Is there a minimum age to rent?", a: "Age and licence experience requirements vary by vehicle class and are listed clearly in each car's details when you search. Younger drivers may see a small daily supplement depending on the model." },
    { q: "What's actually included in the price?", a: "Third-party liability insurance and CDW come standard on most cars. VAT, a roadside safety kit, and a transparent fuel policy are included too. Mileage terms differ per vehicle — check the car listing. Zero-excess cover and extras like child seats can be added at booking." },
    { q: "How does pickup work from the airports?", a: "Podgorica Airport is about 2 hours from Ulcinj, Tivat Airport around 2.5 hours. Your agent meets you at arrivals and drives you to the car. Alternatively, arrange pickup directly in Ulcinj town or at your accommodation." },
    { q: "Can I return the car somewhere different?", a: "One-way rentals are available across 28+ towns and cities in Montenegro. Pick up in Ulcinj, drop off at Podgorica Airport, or vice versa — just select different locations when you book." },
    { q: "What is the cancellation policy?", a: "Standard vehicles: free cancellation up to 7 days before pickup. Luxury cars and convertibles: free cancellation up to 30 days in advance. A 6% processing fee applies on all cancellations regardless of timing." },
    { q: "Do I need to pay a deposit?", a: "It depends on the vehicle. Deposits typically fall between \u20ac100 and \u20ac500 for most rentals. Some cars require no deposit at all. Where one applies, it sits on the main driver's physical credit card and is released when the car is returned undamaged." },
    { q: "What if I go over my mileage allowance?", a: "Vehicles with a set mileage cap charge a per-kilometre fee for any distance above the limit. The exact overage rate is shown in the car details before you confirm — no surprises." },
    { q: "Is the price I see the price I pay?", a: "Yes. All taxes and standard fees are folded into the booking price. There is no fuel surcharge, airport levy, or desk fee added when you collect the car." },
    { q: "How much do I pay to confirm the booking?", a: "A deposit of roughly 15% to 20% of the total secures the reservation. The rest is settled directly with the rental agent when you pick up the car in Ulcinj or at the airport." },
    { q: "Can I rent without a credit card?", a: "Certain vehicles in the fleet can be rented with a debit card or without a card altogether. These are labelled in the search results so you can filter accordingly." },
  ],

  locations: [
    { name: "Ulcinj Old Town", tag: "Most Popular" },
    { name: "Velika Plaza", tag: "Long Beach" },
    { name: "Ada Bojana", tag: "Kitesurfing" },
  ],

  destinations: [
    {
      name: "Velika Plaza",
      slug: "velika-plaza",
      tag: "Long Beach",
      desc: "13 km of sandy beach — the longest on the Adriatic.",
      image: "/img/tivat-airport.webp",
    },
    {
      name: "Ada Bojana",
      slug: "ada-bojana",
      tag: "Kitesurfing",
      desc: "River island and kitesurfing paradise at the Albanian border.",
      image: "/img/kotor-nearby.webp",
    },
    {
      name: "Stari Grad",
      slug: "stari-grad",
      tag: "Old Town",
      desc: "Ottoman-era old town perched above the sea.",
      image: "/img/budva-old-town.webp",
    },
    {
      name: "Valdanos",
      slug: "valdanos",
      tag: "Hidden Gem",
      desc: "Secluded bay surrounded by ancient olive groves.",
      image: "/img/perast-village.webp",
    },
    {
      name: "Bar",
      slug: "bar",
      tag: "Port City",
      desc: "Montenegro's main port — Stari Bar ruins and ferry terminal.",
      image: "/img/porto-montenegro.webp",
    },
    {
      name: "Lake Skadar",
      slug: "lake-skadar",
      tag: "National Park",
      desc: "The Balkans' largest lake — boat trips and birdwatching.",
      image: "/img/podgorica-city.webp",
    },
    {
      name: "Podgorica Airport",
      slug: "podgorica-airport",
      tag: "40 km",
      desc: "Montenegro's main international airport, about 2 hours away.",
      image: "/img/podgorica-airport.webp",
    },
    {
      name: "Shkodra (Albania)",
      slug: "shkodra",
      tag: "Cross-Border",
      desc: "Historic Albanian city — 45 minutes from Ulcinj.",
      image: "/img/dubrovnik-nearby.webp",
    },
  ],
};

export default siteConfig;
